config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create ]

  root 'products#index'

end

app/models/cart.rb
class Cart
	attr_reader :items

	def self.build_from_hash hash
		items = if hash["cart"] then
			hash["cart"]["items"].map do |item_data|
				CartItem.new item_data["product_id"], item_data["quantity"]
			end
		else
			[]
		end

		new items
	end

	def initialize items = []
		@items = items
	end

	def add_item product_id
		item = @items.find { |item| item.product_id == product_id }
		
		if item
			item.increment
		else
			@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def count
		@items.length
	end

	def serialize
		items = @items.map do |item|
			{
				"product_id" => item.product_id,
				"quantity" => item.quantity
			}
		end

		{			
			"items" => items			
		}
	end

	def total_price
		@items.inject(0) { |sum, item| sum + item.total_price }
	end
end

app/models/cart_item.rb
class CartItem
	attr_reader :product_id, :quantity

	def initialize product_id, quantity = 1
		@product_id = product_id
		@quantity = quantity
	end

	def increment
		@quantity = @quantity + 1
	end

	def product
		Product.find product_id
	end

	def total_price
		product.price * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items

  def total_price
  	order_items.inject(0) { |sum, item| sum + item.total_price }
  end
end

app/models/order_form.rb
class OrderForm
	include ActiveModel::Model

	attr_accessor :user, :order #credit_cart
	attr_writer :cart

	def save
		set_password_for_user

		if valid?
			persist
			true
		else
			false
		end
	end

	def has_errors?
		user.errors.any?
	end

	private

		def valid?
			user.valid?
		end

		def persist
			user.save
			@order = Order.create! user: user

			build_order_items
		end

		def set_password_for_user
			user.password = Digest::SHA1.hexdigest(user.email + Time.now.to_s)[0..8]
		end

		def build_order_items
			@cart.items.each do |item|
				@order.order_items.create! product_id: item.product_id, quantity: item.quantity
			end
		end	
	
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  def total_price
  	self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	validates_presence_of :name, :price
	validates_numericality_of :price
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	validates_presence_of :name, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def initialize_cart
  	@cart = Cart.build_from_hash session
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :initialize_cart

	def add
		@cart.add_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		redirect_to :back, notice: "#{product.name} додано до Вашої корзини."
	end

	def show		
	end

	def checkout
		@order_form = OrderForm.new user: User.new
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter :initialize_cart

	def create
		@order_form = OrderForm.new(
			user: User.new(order_params[:user]),
			cart: @cart
		)

		if @order_form.save
			notify_user
			redirect_to root_path, 
				notice: "Дякуємо за Ваше замовлення. Менеджер компанії зателефонує Вам в найкоротший термін."	
		else
			render "carts/checkout"
		end	
	end

	private

		def notify_user
			@order_form.user.send_reset_password_instructions			
			OrderMailer.order_confirmation(@order_form.order).deliver
		end

		def order_params
			params.require(:order_form).permit(
				user: [ :name, :phone, :email ]
			)
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart

  respond_to :html

  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_cart.html.haml
-if @cart
	%p.navbar-text.navbar-right
		-if @cart.empty?
			Ваша корзина порожня.
		-else
			=link_to "У Вашій корзині товару #{@cart.count} шт.", cart_path

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ТеплоМаркет</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">        
        <li class="active"><%= link_to "Каталог", products_path %></li>     
      </ul>
      <%= render "cart" %>          
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/carts/checkout.html.haml
%h1.brand Оформлення замовлення:
	
%h4 Ви замовили наступні позиції:

%ul
	-@cart.items.each do |item|
		%li
			%em
			=item.quantity 
			шт. 
			=item.product.name
			=sprintf("%0.02f", item.total_price)
			грн.
%p

	%strong.brand
		Всього на суму:
		=sprintf("%0.02f", @cart.total_price)
		грн.

=form_for @order_form, url: orders_path do |f|
	=render "orders/errors"
	%h3 Введіть свої данні:
	=f.fields_for :user, f.object.user do |u|
		.form-group
			%p=u.text_field :name, placeholder: "Ім'я", class: "form-control"
			%span.help-block Інформація про Вашу електронну адресу та номер телефону, допоможе Вам відслідковувати Ваше замовлення більш ефективно. 
		.form-group
			%p=u.text_field :phone, placeholder: "Номер телефону", class: "form-control"		
			%p=u.text_field :email, placeholder: "Email", class: "form-control"
			%span.help-block Ми гарантуємо конфеденційність Ваших данних.

		%p=f.submit "Відправити замовлення", class: "btn btn-primary"


app/views/carts/show.html.haml
%table.table.table-hover
	%thead
		%tr			
			%th Найменування
			%th Кількість
			%th Ціна
			%th Всього
		-@cart.items.each do |item|
			%tr				
				%td
					=image_tag item.product.image.thumb
					=link_to item.product.name, item.product
				%td=item.quantity
				%td
					=sprintf("%0.02f", item.product.price)
					грн.
				%td
					=sprintf("%0.02f", item.total_price)
					грн.	
			
%p.text-right.brand.strong
	Всього:
	=sprintf("%0.02f", @cart.total_price)
	грн.

%p=link_to "Оформити замовлення", checkout_cart_path, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "nav" %>
<div class="container">
	<%= content_tag :div, notice, class: "bg-success" %>
	<%= content_tag :div, alert, class: "bg-danger" %>
	<%= yield %>
</div>

</body>
</html>

app/views/orders/_errors.html.haml
-if @order_form.has_errors?
	.panel.panel-danger
		.panel-heading
			%h4.panel-title Вам слід внести деякі поправки в форму.				
		.panel-body
			-@order_form.user.errors.full_messages.each do |error|
				%p
					%strong Користувач:
					=error

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1.brand каталог продукції

%table.table.table-hover
  %thead
    %tr
      %th Найменування
      %th Ціна
      %th Зображення      
      %th
      
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td
          = sprintf("%0.02f", product.price)
          грн.
        %td= image_tag product.image.thumb
        %td          
          = link_to 'Редагувати', edit_product_path(product)
          \|
          = link_to 'Видалити', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%p
  = link_to 'Створити новий продукт', new_product_path, class: "btn btn-xs btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%h1.brand= @product.name

%p
	= image_tag @product.image.b_thumb
%p
	= sprintf("%0.02f", @product.price)
	грн.

%p=link_to "Додати до корзини", add_cart_path, method: :post, class: "btn btn-primary"

%p
	= link_to 'Редагувати', edit_product_path(@product)
	\|
	= link_to 'До каталогу', products_path